### ISSUE TITLE
New Supported Data - ETH/JPY

### ISSUE THREAD

**Issue by 0xsomewherecat** [tellor-io/TIPs#18]
Dear Tellor team,

This is somewherecat from the Yamato Protocol team. We are building JPY stablecoin lending Daap, and we wish to connect with Tellor to receive the ETH/JPY feed.

Daap development landscape is bit delayed in Japan but it is picking up. Hence we believe that adding ETH/JPY feed for the trusted Tellor feed will be valuable for the ecosystem, not only our team.

Can you kindly review our request and let us know if the prepared information is satisfactory? We admire the Tellor product/community and we look forward to hearing from you.

Background of this request (conversation between Mr. Fett and our lead dev 0xMotoko): https://twitter.com/OxMotoko/status/1411510881087725569

**Proposal**	
In the contract, add another request ID	
	
In the miner code, add as a subsequent PSR and the following API's in the indexes.json file. 	
'' "ETH/JPY": [ "json(https://api.coingecko.com/api/v3/simple/price?ids=ethereum&vs_currencies=jpy&include_last_updated_at=true).ethereum.jpy","json(https://api.bitflyer.com/v1/getticker?product_code=ETH_JPY).ltp","json(https://api-pub.bitfinex.com/v2/ticker/tETHJPY)[6]"]"	

**Price source summary (inclusive of the gist for each price source)**	
https://docs.google.com/spreadsheets/d/1lVE4gNNeRZiOsOjRl3u0jBO6u5szxT5ZXDlhsh9AbRA/edit#gid=775297008
	
**Here's quick overview of each suggested price source candidates.**	
1. CoinGecko: Proposed as the primary source as it is an aggregated price from various DEXes & CEXes, considered a fairly stable & objective feed.	
2. Bitflyer: Proposed as the secondary source as it is the biggest CEX in Japan offering the ETH/JPY pair directly, considered a good indication of liquidity.	
3. Bitfinex: Proposed as the tertiary source as it is (probably) the biggest CEX outside Japan offering the ETH/JPY pair directly, considered a good off-shore feed.

**Comment by tkernell** [comment]
This is tkernell/heavychain from the Tellor Team. Thank you for you submission. You seem to have provided satisfactory information and I think you can proceed to submitting a formal proposal draft for community review. See this [this link for an example](https://github.com/tellor-io/TIPs/pull/6/files?w=1).

**Comment by 0xsomewherecat** [comment]
Hello Mr. Kernell/heavychain. Thank you for your prompt review. We're happy to hear that the information is satisfactory to proceed for community review. Following the example, we have submitted a formal proposal draft: https://github.com/tellor-io/TIPs/pull/19.

**Comment by 0xsomewherecat** [comment]
Thank you very much for adding ETH/JPY instrument, Tellor team.

We wish to test this feed in Rinkeby testnet late Aug/early Sep. Can you kindly advise the expected timeline for this change to be available in Rinkeby?

**Comment by tkernell** [comment]
We are happy to add a new data feed to the Tellor system. ETH/JPY price is available right now on Rinkeby and Mainnet at requestId 59.

**Comment by 0xsomewherecat** [comment]
We are very happy and grateful to hear that. Thank you very much again!
