### ISSUE TITLE
New Supported Data - OGN Price

### ISSUE THREAD

**Issue by themandalore** [tellor-io/TIPs#3]

**Comment by themandalore** [comment]
https://github.com/tellor-io/TIPs/blob/tipadditions/TIPs/TIP-3%20New%20Supported%20Data%20-%20OGN.md

**Comment by brendaloya** [comment]
This update was implemented on the Tellor Miner Release v5.2.0: https://github.com/tellor-io/TellorMiner/releases/tag/v5.2.0
