### ISSUE TITLE
New Supported Data - VIX

### ISSUE THREAD

**Issue by themandalore** [tellor-io/TIPs#7]
https://github.com/tellor-io/TIPs/pull/6

**Comment by themandalore** [comment]
https://github.com/tellor-io/TIPs/blob/vix/TIPs/TIP-5%20New%20Supported%20Data%20-%20VIX.md

**Comment by brendaloya** [comment]
This update was implemented on the Tellor Miner Release v5.2.0: https://github.com/tellor-io/TellorMiner/releases/tag/v5.2.0
