### ISSUE TITLE
TIP-6 - v2.6

### ISSUE THREAD

**Issue by themandalore** [tellor-io/TIPs#9]

**Comment by themandalore** [comment]
https://github.com/tellor-io/TIPs/blob/main/TIPs/TIP-X%20Difficulty%20Retargeting.md

**Comment by themandalore** [comment]
Current Plan to Implement difficulty calculation is based on slots 1 - 4

- In submitMiningSolution, if slot = 4, store a new uintVar for tracking this time.  
- In newBlock, change the calculation to check not against the timeOfLastNewValue, but against the new variable. 
- If time for 4 solutions is less than 4 minutes, increase.  If over, decrease
- If slot 5 , diff == 1

**Comment by mikeghen** [comment]
> If slot 5 , diff == 1

Do you think we could add slot progress to `NonceSubmitted` event so miners can listen for `NonceSubmitted` to know when slot progress is 4? Otherwise, the only way to check will be to poll and check uintVars, I think. Idk what the implications of this addition would be though.

**Comment by themandalore** [comment]
> * If slot 5 , diff == 1

As for the reasoning, I think if you have it the same diff for all 5 and 1-4 is the payout. 
If you assume someone solves it very fast and jacks up the difficulty (likely), but they actually have no incentive to submit for block 5 .  In fact, they would want block 5 to take a very long time.  If block5 is 15 minutes each time, they have to submit 4 times to get the same reward as 12 times if the blocks are 5 minutes.  They'd doubly like this too, because then they could even have less stakes as the timeout isn't as long with 15 minute blocks.  So you could easily see a scenario where the party who solves 1-4 is incentivized to push blocktimes as long as possible...which is backward from what the network actually wants

**Comment by themandalore** [comment]
> > If slot 5 , diff == 1
> 
> Do you think we could add slot progress to `NonceSubmitted` event so miners can listen for `NonceSubmitted` to know when slot progress is 4? Otherwise, the only way to check will be to poll and check uintVars, I think. Idk what the implications of this addition would be though.

Yeah I think we can add it relatively cheaply.  Also, adding shouldn't mess up listeners as far as I know either.

**Comment by mrozmanith** [comment]
> https://github.com/tellor-io/TIPs/blob/main/TIPs/TIP-X%20Difficulty%20Retargeting.md

that page is a broken link

**Comment by mikeghen** [comment]
@mrozmanith, its been assigned a #, TIP-6 now instead of TIP-X, here's the link: https://github.com/tellor-io/TIPs/blob/main/TIPs/TIP-6%20Difficulty%20Retargeting.md
